version: "3"
services:
  teq:
    container_name: mysql
    image: mysql:8.0.21
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - example:/var/lib/mysql
    command:
      [
          "mysqld",
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
          "--default-authentication-plugin=mysql_native_password"
      ]
  teq_test:
    container_name: mysql_test
    platform: linux/x86_64
    image: mysql:8.0.21
    environment:
      MYSQL_DATABASE: ${DB_TEST_NAME}
      MYSQL_USER: ${DB_TEST_USERNAME}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_TEST_PASSWORD}
    ports:
      - ${DB_TEST_PORT}:3306
    volumes:
      - example_test:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports: 
      - ${REDIS_PORT}:6379          
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./cachedata/:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis_test:
    container_name: redis_test
    image: redis:latest
    restart: always
    ports: 
      - ${REDIS_TEST_PORT}:6379          
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./cachedata/:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  example:
  example_test:
