// Code generated by mockery v2.36.0. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockICache is an autogenerated mock type for the ICache type
type MockICache struct {
	mock.Mock
}

type MockICache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICache) EXPECT() *MockICache_Expecter {
	return &MockICache_Expecter{mock: &_m.Mock}
}

// NewMockICache creates a new instance of MockICache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICache {
	mock := &MockICache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
