// Code generated by mockery v2.36.0. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockRegisterService is an autogenerated mock type for the RegisterService type
type MockRegisterService struct {
	mock.Mock
}

type MockRegisterService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegisterService) EXPECT() *MockRegisterService_Expecter {
	return &MockRegisterService_Expecter{mock: &_m.Mock}
}

// NewMockRegisterService creates a new instance of MockRegisterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegisterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegisterService {
	mock := &MockRegisterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
