// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/teq.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TeqServiceClient is the client API for TeqService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeqServiceClient interface {
	GetExampleByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
}

type teqServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeqServiceClient(cc grpc.ClientConnInterface) TeqServiceClient {
	return &teqServiceClient{cc}
}

func (c *teqServiceClient) GetExampleByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, "/TeqService/GetExampleByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeqServiceServer is the server API for TeqService service.
// All implementations must embed UnimplementedTeqServiceServer
// for forward compatibility
type TeqServiceServer interface {
	GetExampleByID(context.Context, *GetByIDRequest) (*ExampleResponse, error)
	mustEmbedUnimplementedTeqServiceServer()
}

// UnimplementedTeqServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTeqServiceServer struct {
}

func (UnimplementedTeqServiceServer) GetExampleByID(context.Context, *GetByIDRequest) (*ExampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExampleByID not implemented")
}
func (UnimplementedTeqServiceServer) mustEmbedUnimplementedTeqServiceServer() {}

// UnsafeTeqServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeqServiceServer will
// result in compilation errors.
type UnsafeTeqServiceServer interface {
	mustEmbedUnimplementedTeqServiceServer()
}

func RegisterTeqServiceServer(s grpc.ServiceRegistrar, srv TeqServiceServer) {
	s.RegisterService(&TeqService_ServiceDesc, srv)
}

func _TeqService_GetExampleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeqServiceServer).GetExampleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TeqService/GetExampleByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeqServiceServer).GetExampleByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeqService_ServiceDesc is the grpc.ServiceDesc for TeqService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeqService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TeqService",
	HandlerType: (*TeqServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExampleByID",
			Handler:    _TeqService_GetExampleByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/teq.proto",
}
